api_login_check:
    path: /api/auth/login_check
    methods: [POST]
api:
    resource: ../src/Controller/Api/
    prefix: /api
    name_prefix: api.
    trailing_slash_on_root: true
    type: annotation
    defaults:
        _format: json

controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation